[2021-03-09 11:34:55,933] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: extract_standings.load_standings 2021-03-09T17:34:49.014505+00:00 [queued]>
[2021-03-09 11:34:55,938] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: extract_standings.load_standings 2021-03-09T17:34:49.014505+00:00 [queued]>
[2021-03-09 11:34:55,939] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-09 11:34:55,939] {taskinstance.py:1043} INFO - Starting attempt 1 of 3
[2021-03-09 11:34:55,939] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-09 11:34:55,945] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): load_standings> on 2021-03-09T17:34:49.014505+00:00
[2021-03-09 11:34:55,947] {standard_task_runner.py:52} INFO - Started process 27688 to run task
[2021-03-09 11:34:55,955] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'extract_standings', 'load_standings', '2021-03-09T17:34:49.014505+00:00', '--job-id', '143', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standings_dag.py', '--cfg-path', '/var/folders/n1/tvvct6mn75xbwwwl4s02tfdc0000gn/T/tmp39b0cl5f', '--error-file', '/var/folders/n1/tvvct6mn75xbwwwl4s02tfdc0000gn/T/tmpe9lb_5u8']
[2021-03-09 11:34:55,959] {standard_task_runner.py:77} INFO - Job 143: Subtask load_standings
[2021-03-09 11:34:55,991] {logging_mixin.py:104} INFO - Running <TaskInstance: extract_standings.load_standings 2021-03-09T17:34:49.014505+00:00 [running]> on host 25.1.168.192.in-addr.arpa
[2021-03-09 11:34:56,017] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AWTY
AIRFLOW_CTX_DAG_ID=extract_standings
AIRFLOW_CTX_TASK_ID=load_standings
AIRFLOW_CTX_EXECUTION_DATE=2021-03-09T17:34:49.014505+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-09T17:34:49.014505+00:00
[2021-03-09 11:34:56,018] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/n1/tvvct6mn75xbwwwl4s02tfdc0000gn/T
[2021-03-09 11:34:56,019] {bash.py:158} INFO - Running command: curl --header "Content-Type: application/json" --request POST --data @./standings_dump.json http://127.0.0.1:4321/db/update
[2021-03-09 11:34:56,026] {bash.py:169} INFO - Output:
[2021-03-09 11:34:56,033] {bash.py:173} INFO - Warning: Couldn't read data from file "./standings_dump.json", this makes an
[2021-03-09 11:34:56,034] {bash.py:173} INFO - Warning: empty POST.
[2021-03-09 11:34:56,034] {bash.py:173} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2021-03-09 11:34:56,034] {bash.py:173} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2021-03-09 11:34:56,038] {bash.py:173} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   192  100   192    0     0  48000      0 --:--:-- --:--:-- --:--:-- 48000
[2021-03-09 11:34:56,039] {bash.py:173} INFO - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
[2021-03-09 11:34:56,039] {bash.py:173} INFO - <title>400 Bad Request</title>
[2021-03-09 11:34:56,039] {bash.py:173} INFO - <h1>Bad Request</h1>
[2021-03-09 11:34:56,040] {bash.py:173} INFO - <p>The browser (or proxy) sent a request that this server could not understand.</p>
[2021-03-09 11:34:56,040] {bash.py:177} INFO - Command exited with return code 0
[2021-03-09 11:34:56,051] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=extract_standings, task_id=load_standings, execution_date=20210309T173449, start_date=20210309T173455, end_date=20210309T173456
[2021-03-09 11:34:56,061] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-09 11:34:56,099] {local_task_job.py:146} INFO - Task exited with return code 0
